### ISSUE TITLE
Update to v4.3

### ISSUE THREAD

**Issue by aleksrutins** [mkizka/mastodon-railway-template#15]
Mastodon v4.3.x has been out for a while at this point, but this template is still stuck on v4.2.13. Any chance of an update?

**Comment by mkizka** [comment]
Thank you for opening an issue. Unfortunately, I am unable to maintain this repository as I am working on other projects.  

In Mastodon v4.3.0, there seem to be some changes in the Docker structure, and the Node.js execution binary has been moved to `mastodon-streaming`. Because of this, the `concurrently` command can no longer be used. Fixing this issue would require a review of the template's configuration, but I currently don't have the time to work on it.  
> The Docker image has been split in two separate images
> https://github.com/mastodon/mastodon/releases/tag/v4.3.0

I’m sorry, but please consider forking this project and fixing it yourself if needed. I will update this template to indicate that it is deprecated.
